server:
  port: 8080

spring:          #表示该配置直接为Spring容器负责处理
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
  　　driver-class-name: org.gjt.mm.mysql.Driver       #配置MySQL的驱动程序类
  　　url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
  　　username: root
  　　password: root
